import { IconData } from '../types'

export type IconMeta = {
  exportName: string
  useId: string
  format: 'font' | 'svg'
  relativePath: string
}

export type Conflict = {
  reason: 'duplicate' | 'invalid-name'
  exportName?: string
  paths: string[]
}

/** kebab/任意分隔 → `Icon` + PascalCase。`home`→`IconHome`、`arrow-left`→`IconArrowLeft`、`4k`→`Icon4k`。 */
export function toExportName(id: string): string {
  const pascal = id
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('')
  return 'Icon' + pascal
}

/** 合并 font+svg 列表 → 导出元信息;检测全局命名冲突与非法名。 */
export function buildIconMetas(iconList: IconData): { metas: IconMeta[]; conflicts: Conflict[] } {
  const metas: IconMeta[] = []
  const byName = new Map<string, IconMeta>()
  const conflicts: Conflict[] = []
  for (const item of iconList) {
    const exportName = toExportName(item.id)
    if (exportName === 'Icon') {
      conflicts.push({ reason: 'invalid-name', paths: [item.relativePath] })
      continue
    }
    const existing = byName.get(exportName)
    if (existing) {
      conflicts.push({
        reason: 'duplicate',
        exportName,
        paths: [existing.relativePath, item.relativePath]
      })
      continue
    }
    const meta: IconMeta = {
      exportName,
      useId: item.useId,
      format: item.format,
      relativePath: item.relativePath
    }
    byName.set(exportName, meta)
    metas.push(meta)
  }
  return { metas, conflicts }
}

function componentCode(m: IconMeta): string {
  const head =
    `export const ${m.exportName} = /*@__PURE__*/ defineComponent({\n` +
    `  name: ${JSON.stringify(m.exportName)},\n` +
    `  props: { size: { default: '1em' }, color: { default: undefined } },\n`
  if (m.format === 'svg') {
    return (
      head +
      `  setup(props) { return () => h('svg', { width: props.size, height: props.size, style: { color: props.color } }, [h('use', { href: '#${m.useId}' })]) }\n` +
      `})`
    )
  }
  return (
    head +
    `  setup(props) { return () => h('i', { class: ${JSON.stringify(m.useId)}, style: { fontSize: props.size, color: props.color } }) }\n` +
    `})`
  )
}

/** 组件 barrel:具名 const 导出,Rollup 可在语句级摇除未用到的。 */
export function generateBarrel(metas: IconMeta[]): string {
  const lines = [`import { defineComponent, h } from 'vue'`]
  for (const m of metas) lines.push(componentCode(m))
  return lines.join('\n')
}

/** `.d.ts`:声明 `virtual:supericon` 的具名组件导出。 */
export function generateDts(metas: IconMeta[]): string {
  const lines = [
    `// AUTO-GENERATED by vite-plugin-supericon. Do not edit.`,
    `// import 'virtual:supericon/register' once at your app entry to load font css + svg sprite.`,
    `declare module 'virtual:supericon' {`,
    `  import type { DefineComponent } from 'vue'`,
    `  export type SuperIconProps = { size?: string | number; color?: string }`
  ]
  for (const m of metas) lines.push(`  export const ${m.exportName}: DefineComponent<SuperIconProps>`)
  lines.push(`}`)
  lines.push(`declare module 'virtual:supericon/register' {}`)
  return lines.join('\n') + '\n'
}
